# Generated by Django 3.2.6 on 2021-10-05 14:10

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.TestUpload.image),
        ),
    ]
