# Generated by Django 4.2.6 on 2023-10-30 01:56

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20211005_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.TestUpload.image),
        ),
    ]
