# Generated by Django 3.2.6 on 2021-09-28 05:35

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_testupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.TestUpload.image),
        ),
    ]
